### ISSUE TITLE
F. 107 No deja crear una nueva plantillas para un registro en hoja de calculo, solo sale el titulo Nueva Plantillahcr

### ISSUE THREAD

**Issue by pmartinez55** [pasosdeJesus/si_anzorc#107]
![SI IAP 2-0b13 19-1-2021 19-38-23](https://user-images.githubusercontent.com/77182316/105111228-759cd380-5a8e-11eb-8b9b-eb9c53b6e5f8.png)

**Comment by vtamara** [comment]
No reproducible
