### ISSUE TITLE
F-113 En actividad, en listado de asistencia al agregar una persona presenta y agregar un rango de edad presenta error, se cierra la plagina 

### ISSUE THREAD

**Issue by pmartinez5** [pasosdeJesus/si_anzorc#116]
![Captura de pantalla de 2021-01-27 23-10-56](https://user-images.githubusercontent.com/61369119/106145043-0fc1e300-6143-11eb-8591-c48f1f8d75ee.png)

**Comment by vtamara** [comment]
Resuelta.
