### ISSUE TITLE
F-93 Al pulsar en Actividades y proyectos >> Listado de proyectos >> Nuevo genera error

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/si_anzorc#93]
![Captura de pantalla de 2020-12-28 18-08-11](https://user-images.githubusercontent.com/10052756/103248327-2c96ab00-4938-11eb-8a44-4400e8a3b7e6.png)

**Comment by vtamara** [comment]
No reproducible.
