### ISSUE TITLE
F-97 En actividades al agregar rango de edad mujeres, hombres, otros no guarda y genera error en rol operador

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/si_anzorc#97]
![Captura de pantalla de 2020-12-29 20-08-22](https://user-images.githubusercontent.com/10052756/103323688-2543d000-4a12-11eb-8ab7-9ba8da006d78.png)

**Comment by vtamara** [comment]
Gracias. Resuelto.
